variables:
  GOPATH: /go
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: flare_ftso_indexer_test
  GOLANG_VERSION: "1.21"
  GOLINT_VERSION: "v1.55.2"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ${GOPATH}/pkg/mod
    - ${GOPATH}/bin


build:
  stage: build
  image: golang:${GOLANG_VERSION}
  needs: []
  script:
    - go build ./...

lint:
  stage: test
  needs: []
  image: golangci/golangci-lint:${GOLINT_VERSION}
  script:
    - '! gofmt -l . | grep -q .'
    - golangci-lint run --timeout 5m0s

test:
  stage: test
  image: golang:${GOLANG_VERSION}
  needs: []
  variables:
    DB_HOST: mysql
    DB_PORT: 3306
    DB_NAME: ${MYSQL_DATABASE}
    DB_USERNAME: root
    DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    MOCK_CHAIN_PORT: 2426
  services:
    - mysql:latest
  script:
    - go test ./indexer

build-container:
  stage: build
  needs: []
  image: gcr.si/cts/build-oci:1.3.0@sha256:af8fd5a7f8bf74037741f8a831209d66078d94251dd155df6d61b61a9f922bf7
  script: [ "/build.sh" ]
  variables:
    CTS_BUILD_CACHE_REPO: ${CI_REGISTRY_IMAGE}/cache
    CTS_BUILD_DOCKERFILE: Dockerfile
  rules:
  - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    variables:
      CTS_BUILD_TAG: latest
  - if: $CI_COMMIT_TAG != null
    variables:
      CTS_BUILD_TAG: $CI_COMMIT_TAG
  - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
    variables:
      CTS_BUILD_TAG: $CI_COMMIT_REF_SLUG
