stages:
  - build
  - test

variables:
  GOPATH: /go
  MYSQL_ROOT_PASSWORD: root

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ${GOPATH}/pkg/mod
    - ${GOPATH}/bin

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2

Build:
  stage: build
  image: golang:1.21
  script:
    - '! gofmt -l . | grep -q .'
    - golangci-lint run --timeout 5m0s
    - go build ./...

Test:
  stage: test
  image: golang:1.21
  services:
    - mysql:latest
  script:
    - sleep 10  # Wait for MySQL to fully start
    - go test ./...
