[db]
host = "localhost"
port = 3306
database = "flare_ftso_indexer_songbird"
username = "root"
password = "root"
log_queries = false
# history_drop = 604800                    # 7 days

[logger]
level = "INFO"
file = "../logger/logs/flare-ftso-indexer_benchmark.log"
console = true

[chain]
node_url = "https://songbird-node2.flare.space/ext/C/rpc"
# node_url = "wss://songbird-node2.flare.space/ext/C/ws"

[indexer]
start_index = 46199000
stop_index = 0
new_block_check_millis = 1000
batch_size = 2500
num_parallel_req = 250
timeout_millis = 1000
collect = [
    [
        "1000000000000000000000000000000000000003",
        "60848b44",
        true,
        true,
    ],
    [
        "1000000000000000000000000000000000000003",
        "c5adc539",
        true,
        true,
    ],
]
