[db]
host = "localhost"
port = 3306
database = "flare_ftso_indexer_songbird"
username = "root"
password = "root"
log_queries = false
opt_tables = ""

[logger]
level = "INFO"
file = "../logger/logs/flare-ftso-indexer_benchmark.log"
console = true

[chain]
node_url = "https://songbird-node2.flare.space/ext/C/rpc"

[epochs]
first_epoch_start_sec = 1636070400
epoch_duration_sec = 90

[indexer]
start_index = 30000001
stop_index = 30010000
new_block_check_millis = 1000
batch_size = 2500
num_parallel_req = 250
timeout_millis = 500
receipts = ""                 # can be "all"
