# This file serves as a template for the configuration file. Copy it and edit the values as needed.
# Use --config parameter to specify the path to the configuration file.

[indexer]
start_index = 0
new_block_check_millis = 1000
batch_size = 1000
num_parallel_req = 10
log_range = 10

[[indexer.collect_transactions]]
contract_address = "22474d350ec2da53d717e30b96e9a2b7628ede5b"
func_sig = "f14fcbc8"
status = true
collect_events = true

[[indexer.collect_transactions]]
contract_address = "22474d350ec2da53d717e30b96e9a2b7628ede5b"
func_sig = "4369af80"
status = true
collect_events = true

[[indexer.collect_transactions]]
contract_address = "22474d350ec2da53d717e30b96e9a2b7628ede5b"
func_sig = "46f073cf"
status = true
collect_events = true

[[indexer.collect_transactions]]
contract_address = "22474d350ec2da53d717e30b96e9a2b7628ede5b"
func_sig = "901d0e19"
status = true
collect_events = true

[[indexer.collect_transactions]]
contract_address = "b682deef4f8e298d86bfc3e21f50c675151fb974"
func_sig = "2636434d"
status = true
collect_events = true

[[indexer.collect_logs]]
contract_address = "b682deef4f8e298d86bfc3e21f50c675151fb974"
topic = "undefined"


[db]
host = "localhost"
port = 3306
database = "flare_ftso_indexer"
username = "root"
password = "root"
log_queries = false
history_drop = 604800           # 7 days
drop_table_at_start = true

[logger]
level = "INFO"
file = "./logger/logs/flare-ftso-indexer.log"
console = true

[chain]
node_url = "http://127.0.0.1:8545/"

[timeout]
backoff_max_elapsed_time_seconds = 300
timeout_milis = 1000
