name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  BuildAndTestLibrary:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.0

      - name: Build
        run: go build
      - name: Test
        run: |
          cd database/docker
          docker-compose up --detach
          cd ../../indexer 
          go test .
